### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by re-se** [re-se/Ender#5]
- [ ] パーサ
- [ ] React Component

**Comment by se-se** [comment]
* config に default の設定を追加
  - base config を指定できるようにする
* config.json の path を実行時の引数で指定できるようにする

-> test dir に1テスト1ディレクトリ ディレクトリごとに config.json をかく

**Comment by se-se** [comment]
* [ ] 文字, 画像, 音声... について、手動, オート, skip で実行可能か
